Feat product list page front end
Software-Engineering-2021-P9/solidarity-purchasing-group-P09 pull request #10
Opened 2021-11-12 13:59 UTC by MrGreensushi

2021-11-14 14:40 UTC, AdrianaProvenzano requested changes

2021-11-14 14:40 UTC, AdrianaProvenzano commented on client/src/ui-components/ProductListpageComponents/ProductCardComponent/ProductCard.js
> +              </Card.Text>
- In some cards "Price: 1 €" is in the previous line and not in a new one as if the "\n" didn't work 
- Print also packaging information: for example "Packaging: 1kg MOCK"

2021-11-14 14:40 UTC, AdrianaProvenzano commented on client/src/pages/ProductListPage.js
> +  }
Call in a different way the input parameters of updateProducts because sonar doesn't like in this way

2021-11-14 14:40 UTC, AdrianaProvenzano commented on client/src/ui-components/ProductListpageComponents/ProductCardComponent/ProductCard.js
> +        </Card.Footer>
remove this part, I don't think it's useful

2021-11-14 14:45 UTC, AdrianaProvenzano requested changes

2021-11-14 14:45 UTC, AdrianaProvenzano commented on client/src/ui-components/ProductListpageComponents/ProductCardComponent/ProductCard.js
> +    }
It is requested a default case

2021-11-14 14:45 UTC, AdrianaProvenzano commented on client/src/ui-components/ProductListpageComponents/ProductCardComponent/ProductCard.js
> +  }, [props.product]);
I don't think the card needs to maintain the product as a status

2021-11-14 18:47 UTC, G-Salviati requested changes

2021-11-14 18:47 UTC, G-Salviati commented on client/src/pages/ProductListPage.js
> +  const [searcString, setSearchString] = useState();
missing an h for searchString

2021-11-14 18:47 UTC, G-Salviati commented on client/src/pages/ProductListPage.js
> +  }, [category, searcString]);
missing an h for searchString

2021-11-14 18:47 UTC, G-Salviati commented on client/src/services/models/Product.js
> +  static fromMongoJSON(json) {
I don't know if this method should be called fromMongoJSON. It creates the object from the http response not from the MongoDB response.

2021-11-14 18:47 UTC, G-Salviati commented on client/src/services/models/Product.js
> +    this.description = description;
maybe you can hardcode here price and quantity. Not sure

2021-11-15 14:03 UTC, AdrianaProvenzano approved these changes

2021-11-15 15:16 UTC, G-Salviati approved these changes
I think everything is fine now

2021-11-15 15:43 UTC, merged