login frontend
Software-Engineering-2021-P9/solidarity-purchasing-group-P09 pull request #42
Opened 2021-11-26 12:08 UTC by akipekoren

2021-11-26 14:17 UTC, MrGreensushi requested changes
Your page is a bit different from UI-design:
![image](https://user-images.githubusercontent.com/75216840/143593625-97ee6ff6-4461-4343-8ebd-656386b8c95d.png)

The login form doesn't accept '@' as a character: big problem if the login is done via email

2021-11-26 14:17 UTC, MrGreensushi commented on client/src/ui-components/LoginFormComponent/LoginForm.js
> +          </Button>
Fo the Button use the UI-component Button, it already has its own CSS

2021-11-28 12:41 UTC, MarcoBramini requested changes, later dismissed
This PR needs to be updated to stick to the new login architecture.
Look at the userloginpage, has everything needed for the login but is missing the UI (I'm talking about the page with just the buttons to try different users)

2021-12-05 13:19 UTC, akipekoren commented
<img width="1162" alt="Screen Shot 2021-12-05 at 14 19 02" src="https://user-images.githubusercontent.com/50779224/144748192-2434ec95-038a-4fe6-a2fe-0efc3f7e8b85.png">

2021-12-06 10:13 UTC, MrGreensushi approved these changes

2021-12-06 10:20 UTC, merged