Feat not covered orders
Software-Engineering-2021-P9/solidarity-purchasing-group-P09 pull request #52
Opened 2021-11-29 11:58 UTC by AndreaSR95

2021-11-29 14:16 UTC, MrGreensushi requested changes
80% coverage is a little bit low, add more tests

2021-11-29 14:16 UTC, MrGreensushi commented on client/src/ui-components/ClientOrdersComponent/ClientOrderTableRow.js
> +    case("PREPARED"):
instead of using a string create an Enum in the order model and use it

2021-11-29 14:16 UTC, MrGreensushi commented on client/src/ui-components/ClientOrdersComponent/ClientOrderTableRow.js
> +    case("NOT COVERED"):
same as before

2021-11-29 14:16 UTC, MrGreensushi commented on server/dao/order.js
> +}
No need to make it so generic since you only used it to make Orders WAITIN. It's better to make it more specific: given an orderID it will update its status to WAITING if it was NOT COVERED.
Also, you don't need to return the updated object since you do not check anything on the result (just use updateOne)

2021-11-29 15:42 UTC, MarcoBramini commented on client/src/ui-components/ClientOrdersComponent/ClientOrderTableRow.js
> +    case("PREPARED"):
Copy the order status from the server.

2022-01-11 00:17 UTC, MrGreensushi approved these changes

2022-01-11 00:20 UTC, merged