purchasing process
Software-Engineering-2021-P9/solidarity-purchasing-group-P09 pull request #6
Opened 2021-11-10 11:11 UTC by akipekoren

Order is recorded to database.

To do : Since right now we dont have product prices and quantities, in the future availability should decreased and real product prices should be used(Now all products cost 1 euro).

CreateOrder API input and output format example

INPUT :

 {
    "clientId" : "12321321421421",
    "products" : [{"name" : "apple", "quantity" : 3}, {"name" : "banana", "quantity" : 1}, {"name" : "tomatoes", "quantity" : 2}]
}

OUTPUT :  

{
    "clientId": "12321321421421",
    "products": [
        {
            "name": "apple",
            "quantity": 3
        },
        {
            "name": "banana",
            "quantity": 1
        },
        {
            "name": "tomatoes",
            "quantity": 2
        }
    ],
    "status": "WAITING",
    "totalPrice": 6
}

2021-11-13 10:36 UTC, MrGreensushi requested changes
test.js: 
Add more tests, at least one for each parameter, to test error: 400 bad request- invalid parameters

model/order: it's best to assure that 'products' is always an array (possible fix: "this.products = [...products]")

handlers/order: update createOrderHandler (see 'main' branch to see how ( basically you need to use only try and cath not then)). Add a comment on the  'productPrice' to specify it's just a temporary solution

2021-11-13 15:40 UTC, MrGreensushi requested changes

2021-11-13 15:40 UTC, MrGreensushi commented on server/handlers/order.js
> +  }
These 2 lines can be written in just one line

2021-11-13 15:40 UTC, MrGreensushi commented on server/test/test.js
> +        .send({
Each of these tests is just for the clientId='1'; only one is needed. Instead, add one for  productId, and one for Quantity (ex: quantity=-1)

2021-11-13 15:40 UTC, MrGreensushi commented on server/handlers/order.js
> +  var totalPrice = 0;
Add a comment to specify that 'productPrice' is hardcoded to 1 as a temporary solution

2021-11-13 16:17 UTC, MrGreensushi requested changes
Add an HTTP example of the Post on the folder examples, see the main branch for reference

2021-11-13 16:48 UTC, MrGreensushi requested changes
in the shopping cart, add '€' every time there is a price.

While testing the total amount was wrong

When placing an order, the pop up instead of showing the products id -> quantity
should show the name of the product and its quantity (also the total amount at the end, almost like a receipt)

2021-11-13 16:48 UTC, MrGreensushi commented on client/src/services/ApiOrder.js
> +}
Don't create another API file, add this code in the already  existing ApiClient

2021-11-13 16:48 UTC, MrGreensushi commented on client/src/pages/ProductListPage.js
> +      )}
Specified that this code it's just for debugging purposes

2021-11-13 16:48 UTC, MrGreensushi commented on client/src/pages/ClientDetailsPage.js
> +      )}
Specify that this code it's just for debugging purposes

2021-11-13 17:23 UTC, MrGreensushi requested changes

2021-11-13 17:23 UTC, MrGreensushi commented on client/src/pages/ShoppingCartPage.js
> +  };
In the last PR, getProductById was added, try to use it instead of mock data

2021-11-13 17:23 UTC, MrGreensushi commented on client/src/ui-components/ShoppingCartComponent/ModalOrderConfirmed.js
> +        })}
Not user friendly: use instead the product's name
"output map to send to createOrder" is also not very user friendly

2021-11-13 17:23 UTC, MrGreensushi commented on client/src/ui-components/ShoppingCartComponent/ShoppingCartControlsCSS.css
> +}
when 'send order 'is clicked but the order is not sent, the button becomes blue.
Possible solution: specifies its behaviour with:  .cart-button:focus

2021-11-13 17:32 UTC, MarcoBramini requested changes
Front end cannot be in this PR (also there is already another PR opened for that purpose). Remove all the code out of scope

2021-11-13 17:38 UTC, MrGreensushi commented on client/src/pages/ShoppingCartPage.js
> +  };
to be more specific: to get the products you have to make a get ".../products?ids="+list of all ids divided by a comma

see GetProductsByIDs.http for more examples

2021-11-13 19:15 UTC, MrGreensushi requested changes

2021-11-13 19:15 UTC, MrGreensushi commented on server/handlers/order.js
> +};
When returning, products has `\` all over
`{
  "clientId": "318d971d89d6240eb03742d7",
  "products": "[{\"productId\":\"718d971d89d6240eb03742d7\",\"quantity\":3},{\"productId\":\"298d971d89d6240eb03742d7\",\"quantity\":4}]",
  "status": "WAITING",
  "totalPrice": "7"
}`

this is the result of the example provided.
It should also return the id of the order

2021-11-13 19:15 UTC, MrGreensushi commented on server/handlers/order.js
> +      obj.totalPrice
Return also the id

2021-11-14 08:24 UTC, MrGreensushi approved these changes

2021-11-14 15:21 UTC, MarcoBramini requested changes
You have to stick to the API design. If you think design was wrong and want to propose a change, you have to ask the team and we will talk about it.

2021-11-14 15:21 UTC, MarcoBramini commented on client/src/App.js
> +
Remove this change

2021-11-14 15:21 UTC, MarcoBramini commented on client/src/pages/ProductListPage.js
> +          shoppingCartItems="1"
Remove this change

2021-11-14 15:21 UTC, MarcoBramini commented on server/dao/dao.js
> +exports.createOrder = (clientId, products, status, totalPrice) =>
use clientID instead of clientId (everywhere else ID is uppercase, it is lowercase only in the case it's just "id")

2021-11-14 15:21 UTC, MarcoBramini commented on server/dao/order.js
> +exports.createOrder = async (db, clientId, products, status, totalPrice) => {
clientId => clientID

2021-11-14 15:21 UTC, MarcoBramini commented on server/dao/order.js
> +  const res = await db.collection(orderCollectionName).insertOne(newOrder);
Don't do async await here, let this method only return the promise that will be handled in the handler

2021-11-14 15:21 UTC, MarcoBramini commented on server/examples/CreateOrder.http
> +    { "productId": "718d971d89d6240eb03742d7", "quantity": 3 },
This input payload is wrong. The right format is:
{  
  "clientID": "....",
  "products": {
          "718d971d89d6240eb03742d7":3,
          "298d971d89d6240eb03742d7":4,
          }
}

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/order.js
> +  var isNegativeQuantity = false;
quantity cannot be negative thanks to the validation, this is useless

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/order.js
> +  if (isNegativeQuantity) {
remove this code, for the reason above. A negative quantity is an argument error that must be handled in the validation phase.

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/order.js
> +    totalPrice = totalPrice + product.quantity * productPrice;
```suggestion
    totalPrice += product.quantity * productPrice;
```

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/order.js
> +  obj._id = result;
This is not good, you ll never know if something bad happened on the database on one of the saved document attributes during the insertion.

You have to do a get after the insertion as we did in the createEmployee handler.

-> createOrder (attributes)
-> getOrderByID(orderID)
-> return

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/shared_validators.js
> +exports.productIDPathValidator = body(
This is not productIDPathValidator but orderProductIDsBodyValidator

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/shared_validators.js
> +  "productId must be a Mongo ID"
this line is useless, error must be opaque

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/shared_validators.js
> +exports.productQtyPathValidator = body(
This is not productQtyPathValidator but orderProductQtysBodyValidator

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/shared_validators.js
> +  "quantity must be a positive integer"
as above

2021-11-14 15:21 UTC, MarcoBramini commented on server/handlers/shared_validators.js
> +exports.productsValidator = body("products").isArray();
products is not an array from design. you didn't check that the products object contains at least one item and maximum (a reasonable number here)

2021-11-14 15:29 UTC, AdrianaProvenzano commented on client/src/pages/ProductListPage.js
> +          shoppingCartItems="1"
the Prettier formatter changes the ' in " every time I save this document

2021-11-14 17:16 UTC, MarcoBramini approved these changes

2021-11-14 17:16 UTC, MarcoBramini commented on server/handlers/order.js
> +  productsValidator,
orderProductsBodyValidator

2021-11-14 17:16 UTC, MarcoBramini commented on server/handlers/order.js
> +const { validationResult } = require("express-validator");
kill this line

2021-11-14 18:48 UTC, merged