orders real price
Software-Engineering-2021-P9/solidarity-purchasing-group-P09 pull request #75
Opened 2021-12-12 14:59 UTC by ehsanansarii

The backEnd side of real price of orders.
Associated task:
https://polito-se2-21-09.myjetbrains.com/youtrack/issue/S202109SPG-99

2021-12-13 10:50 UTC, AdrianaProvenzano reviewed
Add in dao/dao.js
```exports.getProductPrice = async (productID, week, year) => {
  const res = await getProductAvailability(db, productID, week, year);
  return res.price;
};```

2021-12-13 10:50 UTC, AdrianaProvenzano commented on server/dao/productAvailability.js
> +
You don't need this function because we have getProductAvailability which returns the whole availability and so the price too

2021-12-13 10:50 UTC, AdrianaProvenzano commented on server/handlers/order.js
> +  //const productPrice = 1;
```
  const [week, year] = getNextWeek(dayjs());
  var totalPrice = 0.0;
  await req.body.products.forEach(async (product) => {
    var productPrice = await dao.getProductPrice(
      product.productID,
      ...getNextWeek(dayjs())
    );
    totalPrice += product.quantity * productPrice;
  });```

2021-12-13 11:24 UTC, AdrianaProvenzano requested changes
modify tests related to POST /orders

2022-01-10 18:00 UTC, MarcoBramini commented
Fixed in #90

2022-01-10 18:00 UTC, closed without merging